### ISSUE TITLE
Writing a code base with vimscript (viml) 9

### ISSUE THREAD

**Issue by trusktr** [Bakudankun/qline.vim#1]
Hello! This is neat! 

I see that you have type declarations in the code. So viml 9 has type syntax now? Is there intellisense for it yet?

**Comment by Bakudankun** [comment]
Thank you!

Yes, Vim9 script has type syntax, but it is still under heavy development and is not ready for develop with. Actually, this plugin shouldn't run on the latest Vim because of the recent changes of Vim9. There is no IntelliSense for sure.

See [the document of Vim9](https://github.com/vim/vim/blob/dcc58e031ded8b846a39146112b9b075cbb977d9/runtime/doc/vim9.txt) for the detail. With its history you can guess how Vim9 changed recently.
